generator/src/main/java/io/github/jwharm/javagi/generator/BindingsGenerator.java, generator/src/main/java/io/github/jwharm/javagi/generator/GirParser.java, generator/src/main/java/io/github/jwharm/javagi/model/CallableType.java, generator/src/main/java/io/github/jwharm/javagi/model/Callback.java, generator/src/main/java/io/github/jwharm/javagi/model/Constructor.java, generator/src/main/java/io/github/jwharm/javagi/model/InstanceParameter.java, generator/src/main/java/io/github/jwharm/javagi/model/Interface.java, generator/src/main/java/io/github/jwharm/javagi/model/Method.java, generator/src/main/java/io/github/jwharm/javagi/model/Parameter.java, generator/src/main/java/io/github/jwharm/javagi/model/Parameters.java, generator/src/main/java/io/github/jwharm/javagi/model/RegisteredType.java, generator/src/main/java/io/github/jwharm/javagi/model/ReturnValue.java, gtk4/build.gradle.kts, gtk4/src/main/java/io/github/jwharm/javagi/PointerBitfield.java, gtk4/src/main/java/module-info.java
Utilize the jetbrains annotations to provide information about parameter and return value.
These annotations allow IDEs to better understand the methods, but are not needed during runtime and are excluded from the dep jar accordingly.
I have not tested whether nullability is properly supported by the data types, but the gir calls for it.
Another annotation of interest is @MagicConstant with flagsFromClass, which could replace the bitfield class, but it is on you to decide whether you want to implement that.
=> Nullability annotations

generator/src/main/java/io/github/jwharm/javagi/JavaGI.java, generator/src/main/java/io/github/jwharm/javagi/generator/BindingsGenerator.java, generator/src/main/java/io/github/jwharm/javagi/model/Alias.java, generator/src/main/java/io/github/jwharm/javagi/model/Class.java, generator/src/main/java/io/github/jwharm/javagi/model/Interface.java, generator/src/main/java/io/github/jwharm/javagi/model/Record.java, generator/src/main/java/io/github/jwharm/javagi/model/RegisteredType.java, generator/src/main/java/io/github/jwharm/javagi/model/Union.java, gtk4/build.gradle.kts, gtk4/src/main/java/io/github/jwharm/javagi/Interop.java
Currently, the Interop class contains explicit references to libraries, which is undesirable if you want to use multiple libraries based on java-gi.
This PR generates a static initializer in the main class of the namespace, which is referenced from static initializers in other classes, and loads the library instead.
=> Unhardcode natives

README.md, buildSrc/src/main/kotlin/java-gi.library-conventions.gradle.kts, generator/build.gradle.kts, glib/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, gstreamer/build.gradle.kts, gtk4/build.gradle.kts
Since Gradle 7.6 is out, the workarounds are no longer needed
=> Update to Gradle 7.6

example/src/main/java/io/github/jwharm/javagi/example/GStreamerExample.java, generator/src/main/java/io/github/jwharm/javagi/generator/GirParser.java, generator/src/main/java/io/github/jwharm/javagi/generator/PatchSet.java, generator/src/main/java/io/github/jwharm/javagi/model/Constructor.java, generator/src/main/java/io/github/jwharm/javagi/model/Function.java, generator/src/main/java/io/github/jwharm/javagi/model/Method.java, generator/src/main/java/io/github/jwharm/javagi/model/Signal.java, generator/src/main/java/io/github/jwharm/javagi/model/Type.java, generator/src/main/java/io/github/jwharm/javagi/model/VirtualMethod.java, gtk4/build.gradle.kts
Some methods have an attribute `shadows` or `shadowed-by`. Language bindings are expected to rename the shadowing method to the name of the shadowed method. The original, shadowed method is not exposed in the bindings.
This uncovered a small issue in the Gtk library, so I added a patch on `GtkWidget` to change the return type of a method from `boolean` to `void` to fix it.
=> Implement function shadowing

buildSrc/src/main/kotlin/ext/GenSourcesExt.kt, buildSrc/src/main/kotlin/ext/JavadocExt.kt, example/src/main/java/io/github/jwharm/javagi/example/Gtk4ListViewExample.java, generator/src/main/java/io/github/jwharm/javagi/generator/PatchSet.java, glib/build.gradle.kts, gstreamer/build.gradle.kts, gtk4/build.gradle.kts
This adds references to the glib Javadoc to the gtk4/gstreamer Javadocs.
These references are generated locally (the version online is not used).
Additionally, I moved some common logic for JavaGI invocation/gradle configuration to buildSrc.
=> Clean up kotlin DSL interface, support javadoc references

example/src/main/java/io/github/jwharm/javagi/example/GStreamerExample.java, example/src/main/java/io/github/jwharm/javagi/example/Gtk4Example.java, example/src/main/java/io/github/jwharm/javagi/example/ListIndexItem.java, example/src/main/java/io/github/jwharm/javagi/example/ListIndexModel.java, generator/src/main/java/io/github/jwharm/javagi/generator/GirParser.java, generator/src/main/java/io/github/jwharm/javagi/model/InstanceParameter.java, generator/src/main/java/io/github/jwharm/javagi/model/Parameter.java, generator/src/main/java/io/github/jwharm/javagi/model/ReturnValue.java, generator/src/main/java/io/github/jwharm/javagi/model/Signal.java
Fixes #35 
Please review; this should improve the detection of `user_data` parameters that can be omitted from the Java API.
The old functionality filters all parameters with type `gpointer` and name ending with `data`, but that resulted in a lot of false positives (for example in `g_list_append`).
=> Detect user_data parameters using 'closure' attribute

buildSrc/src/main/kotlin/java-gi.library-conventions.gradle.kts, generator/src/main/java/io/github/jwharm/javagi/JavaGI.java, generator/src/main/java/io/github/jwharm/javagi/generator/BindingsGenerator.java, generator/src/main/java/io/github/jwharm/javagi/generator/Conversions.java, generator/src/main/java/io/github/jwharm/javagi/generator/Javadoc.java, generator/src/main/java/io/github/jwharm/javagi/generator/PatchSet.java, generator/src/main/java/io/github/jwharm/javagi/generator/SourceWriter.java, generator/src/main/java/io/github/jwharm/javagi/model/Bitfield.java, generator/src/main/java/io/github/jwharm/javagi/model/Class.java, generator/src/main/java/io/github/jwharm/javagi/model/Closure.java, generator/src/main/java/io/github/jwharm/javagi/model/Enumeration.java, generator/src/main/java/io/github/jwharm/javagi/model/Field.java, generator/src/main/java/io/github/jwharm/javagi/model/Interface.java, generator/src/main/java/io/github/jwharm/javagi/model/Method.java, generator/src/main/java/io/github/jwharm/javagi/model/Parameter.java, generator/src/main/java/io/github/jwharm/javagi/model/Parameters.java, generator/src/main/java/io/github/jwharm/javagi/model/Record.java, generator/src/main/java/io/github/jwharm/javagi/model/RegisteredType.java, generator/src/main/java/io/github/jwharm/javagi/model/ReturnValue.java, generator/src/main/java/io/github/jwharm/javagi/model/Signal.java, generator/src/main/java/io/github/jwharm/javagi/model/Type.java, generator/src/main/java/io/github/jwharm/javagi/model/Variable.java, generator/src/main/java/io/github/jwharm/javagi/model/VirtualMethod.java, glib/build.gradle.kts, glib/src/main/java/io/github/jwharm/javagi/base/Alias.java, glib/src/main/java/io/github/jwharm/javagi/interop/Interop.java, glib/src/main/java/io/github/jwharm/javagi/util/ListIndexItem.java, glib/src/main/java/io/github/jwharm/javagi/util/ListIndexModel.java, gstreamer/build.gradle.kts, gtk/build.gradle.kts
Implemented virtual methods.
GObject classes and interfaces can define virtual methods, instance methods and functions:
* Functions are mapped to static methods in Java
* Instance methods are mapped to instance methods in Java
* Virtual methods were not mapped at all until now. Most virtual methods are already implemented by a regular instance method with the same name and type-signature.
However, not all virtual methods have a corresponding instance method defined in the API, so some of them were not available in the Java classes.
With this change, all virtual methods are generated as Java instance methods. The binding retrieves the function pointer from the class struct (or interface struct) and invokes it.
Regular instance methods are now only generated when they don't have the exact …
=> Virtual methods

generator/src/main/java/io/github/jwharm/javagi/generator/BindingsGenerator.java, generator/src/main/java/io/github/jwharm/javagi/model/Alias.java, generator/src/main/java/io/github/jwharm/javagi/model/Bitfield.java, generator/src/main/java/io/github/jwharm/javagi/model/Callback.java, generator/src/main/java/io/github/jwharm/javagi/model/Class.java, generator/src/main/java/io/github/jwharm/javagi/model/Constructor.java, generator/src/main/java/io/github/jwharm/javagi/model/Enumeration.java, generator/src/main/java/io/github/jwharm/javagi/model/Interface.java, generator/src/main/java/io/github/jwharm/javagi/model/Record.java, generator/src/main/java/io/github/jwharm/javagi/model/RegisteredType.java, generator/src/main/java/io/github/jwharm/javagi/model/Type.java, generator/src/main/java/io/github/jwharm/javagi/model/Union.java, generator/src/main/java/io/github/jwharm/javagi/model/Variable.java, glib/src/main/java/io/github/jwharm/javagi/base/GErrorException.java, glib/src/main/java/io/github/jwharm/javagi/base/Signal.java, glib/src/main/java/io/github/jwharm/javagi/interop/InstanceCache.java, glib/src/main/java/io/github/jwharm/javagi/interop/Interop.java, glib/src/main/java/io/github/jwharm/javagi/interop/TypeCache.java, glib/src/main/java/io/github/jwharm/javagi/pointer/PointerProxy.java, glib/src/main/java/io/github/jwharm/javagi/util/JavaClosure.java, glib/src/main/java/io/github/jwharm/javagi/util/ListIndexItem.java, glib/src/main/java/io/github/jwharm/javagi/util/ListIndexModel.java, glib/src/main/java/io/github/jwharm/javagi/util/ValueUtil.java
Add an InstanceCache class that saves a mapping of memory addresses with proxy object instances in a HashMap. Expired entries are removed with toggle references.
This also removes the `fromAddress` method from the generated class definitions. Proxy objects can now simply be instantiated with `InstanceCache.get(address, fallbackConstructor)` or if you don't want to have a cached object, simply with the default MemoryAddress constructor in the proxy class.
=> Implement instance cache

adwaita/build.gradle.kts, buildSrc/src/main/kotlin/ext/RunCommandExt.kt, buildSrc/src/main/kotlin/java-gi.library-conventions.gradle.kts, glib/build.gradle.kts, gstreamer/build.gradle.kts, gtk/build.gradle.kts
Jar files will have two versions: [native library version]-[java-gi version]
For example: `adwaita-1.2.0-0.4.jar`
Javadoc and Sources jars will also change to this naming scheme.
=> Add native library version to jar filename

example/src/main/java/io/github/jwharm/javagi/example/Gtk4Example.java, example/src/main/java/io/github/jwharm/javagi/example/Gtk4TimerExample.java, example/src/main/java/io/github/jwharm/javagi/example/HelloWorld.java, example/src/main/java/module-info.java, generator/src/main/java/io/github/jwharm/javagi/model/Record.java
Changed typeclasses in Java to extend the parent typeclass. For example, let `GtkButtonClass` extend `WidgetClass`. This makes it easier to override virtual methods.
=> Typeclass inheritance

generator/src/main/java/io/github/jwharm/javagi/model/Record.java, glib/src/main/java/io/github/jwharm/javagi/annotations/InterfaceInit.java, glib/src/main/java/io/github/jwharm/javagi/util/ListIndexModel.java, glib/src/main/java/io/github/jwharm/javagi/util/Types.java
When calling `Types.register(my.class)`, and the class implements interfaces with a `TypeInterface` definition, the methods from the interface will automatically be overridden with the Java method implementations in the class.
For every implemented interface, an interface init method can be defined, analogous to class initializers. For example, when implementing `ListModel`:
```java
@InterfaceInit
public static void initialize(ListModelInterface iface) {
...
}
```
=> Implement interfaces when registering new GTypes

generator/src/main/java/io/github/jwharm/javagi/model/Parameter.java, generator/src/main/java/io/github/jwharm/javagi/model/Record.java, generator/src/main/java/io/github/jwharm/javagi/model/RegisteredType.java, generator/src/main/java/io/github/jwharm/javagi/model/ReturnValue.java, generator/src/main/java/io/github/jwharm/javagi/model/Union.java, glib/src/main/java/io/github/jwharm/javagi/base/Floating.java, glib/src/main/java/io/github/jwharm/javagi/base/FreeFunc.java, glib/src/main/java/io/github/jwharm/javagi/base/ProxyInstanceCleanable.java, glib/src/main/java/io/github/jwharm/javagi/interop/InstanceCache.java
Use a Cleaner to call `g_free`, or `[struct_name]_free` when it exists, on structs when the Proxy object is garbage-collected.
=> Free structs

glib/build.gradle.kts, glib/src/main/java/io/github/jwharm/javagi/annotations/Property.java, glib/src/main/java/io/github/jwharm/javagi/util/ListIndexModel.java, glib/src/main/java/io/github/jwharm/javagi/util/Types.java, glib/src/main/java/io/github/jwharm/javagi/util/ValueUtil.java, gtk/src/main/java/io/github/jwharm/javagi/gtk/util/Types.java
This adds a new `@Property` annotation that can be used with getter and setter methods in Java code to define GObject properties.
Example usage:
```java
@Property(name = "n-items", type = ParamSpecInt.class, writable = false)
public int getNItems() {
return items.size();
}
```
The property definitions in the `ListIndexModel` utility class now use this annotation.
=> Annotation to define GObject properties

buildSrc/src/main/java/io/github/jwharm/javagi/patches/GObjectPatch.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/ValueToStringTest.java
Adds a `toString()` method to `org.gnome.gobject.Value` that calls [`g_strdup_value_contents`](https://docs.gtk.org/gobject/func.strdup_value_contents.html).
=> Add Value.toString()

README.md, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/annotations/Property.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Properties.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/DerivedClassTest.java, website/docs/register.md
Make the "name" parameter of the `@Property` annotation optional, and infer the property name from the method names.
The following example:
```java
@Property(name="current-angle")
public double getCurrentAngle() {
return this.angle;
}
@property(name="current-angle")
public double setCurrentAngle(double angle) {
this.angle = angle;
}
```
is equivalent to:
```java
@Property
public double getCurrentAngle() {
return this.angle;
}
@property
public double setCurrentAngle(double angle) {
this.angle = angle;
}
```
The property name will be inferred from the method name:
- Both methods must be regular getters and setters, following the `getX`/`setX` naming pattern
- Java-GI will strip the get/set prefix from the method name and convert the remaining part from CamelCase to kebab-case.
=> Inferred property names

buildSrc/src/main/java/io/github/jwharm/javagi/GenerateSources.java, buildSrc/src/main/java/io/github/jwharm/javagi/generator/Merge.java, modules/gdk/build.gradle, modules/harfbuzz/build.gradle, modules/pango/build.gradle, modules/pangocairo/build.gradle
The dependency on the cairo java bindings is upgraded from 1.16.2 to 1.18.0.
As of release 1.18.0 of the cairo java bindings, the `get_type()` functions from cairo-gobject are included. This fixes an issue when compiling Java-GI with gir files from GNOME 45.
=> Upgrade cairo to 1.18.0

buildSrc/src/main/java/io/github/jwharm/javagi/generator/Conversions.java, buildSrc/src/main/java/io/github/jwharm/javagi/model/Property.java, buildSrc/src/main/java/io/github/jwharm/javagi/model/ValueWrapper.java
Currently the builders use property names as method names:
```java
var box = Box.builder()
.orientation(Orientation.VERTICAL)
.halign(Align.CENTER)
.valign(Align.CENTER)
.build();
```
This is nice to use in Java. However, there are some disadvantages too:
1. Several other JVM languages have special syntax for JavaBean-style setters, like Kotlin *synthetic properties* and the Clojure `bean` function, that don't work with this naming pattern.
2. Although some Java API's (like `java.lang.ProcessBuilder`) use the shorter syntax, most Java developers are used to the `setXxx()` syntax.
Therefore, the builders will now use  the `setXxx()` naming pattern:
```java
var box = Box.builder()
.setOrientation(Orientation.VERTICAL)
.setHalign(Align.CENTER)
.setValign(Align.CENTER)
.build();
```
The …
=> Use setter syntax in builder classes

buildSrc/src/main/java/io/github/jwharm/javagi/generator/Builder.java, buildSrc/src/main/java/io/github/jwharm/javagi/generator/Conversions.java, buildSrc/src/main/java/io/github/jwharm/javagi/generator/Javadoc.java
HarfBuzz types are postfixed with `_t` in C, like `hb_font_t`. This leads to Java types like `FontT`. The trailing `T` is unnecessary and doesn't look very nice. With this change, the HarfBuzz types in Java will loose the trailing `T` so `hb_font_t` will generate a Java `Font` class. The change is not specific for HarfBuzz, but will apply to all type names ending with `_t`.
=> Generate better Harfbuzz type names

buildSrc/src/main/groovy/java-gi.library-conventions.gradle, buildSrc/src/main/java/io/github/jwharm/javagi/generator/Patch.java, buildSrc/src/main/java/io/github/jwharm/javagi/model/GirElement.java, buildSrc/src/main/java/io/github/jwharm/javagi/model/Method.java, buildSrc/src/main/java/io/github/jwharm/javagi/model/ReturnValue.java, buildSrc/src/main/java/io/github/jwharm/javagi/model/Variable.java, buildSrc/src/main/java/io/github/jwharm/javagi/model/VirtualMethod.java, buildSrc/src/main/java/io/github/jwharm/javagi/patches/GioPatch.java, buildSrc/src/main/java/io/github/jwharm/javagi/patches/GstAudioPatch.java, buildSrc/src/main/java/io/github/jwharm/javagi/patches/GstVideoPatch.java, buildSrc/src/main/java/io/github/jwharm/javagi/patches/GtkPatch.java, buildSrc/src/main/java/io/github/jwharm/javagi/patches/SoupPatch.java
In a few situations, we need to override the return type of a method:
- When a method in a subclass overrides a method in a superclass, with a different return type
- When an instance method and virtual method in the same class and the same name have differnt return types.
In previous Java-GI versions, the return type would be updated with a patch, but that would also impact the actual call to the native function. That can lead to segfaults. So with this PR, the return type of the Java bindings is changed, but the native function invocation still uses the type signature as declared in the GIR file.
The following return types are changed:
- `void GtkMediaStream.play()` returns void, but a virtual method with the same name returns `gboolean`. The instance method now also returns `gboolean` …
=> Return type overrides

buildSrc/src/main/groovy/java-gi.library-conventions.gradle, buildSrc/src/main/java/io/github/jwharm/javagi/generators/RecordGenerator.java, buildSrc/src/main/java/io/github/jwharm/javagi/generators/UnionGenerator.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Properties.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Signals.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Types.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/DerivedClassTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/ValueToStringTest.java
Generate constructors to replace the `allocate()` factory methods on records (structs). The old methods are still available (but deprecated).
This adds a constructor for union types as well.
=> Value type constructors

website/docs/generate.md
This is a recreation of #92
I re-added the warnings for users in the guide that shows how to generate bindings. I also fixed several grammar issues and inconsistencies.
=> Improve grammar and include warnings for users in docs

.github/workflows/windows-gtk.yml
The old script seems to have broken due to changes either in GTK or the GitHub Actions Windows runner.
This should make it work again, so creating new builds should be possible.
Also: I just noticed I still have push access to this repo. Since I don't contribute actively anymore, you should probably remove it, just to be safe.
=> Make the windows-gtk action work again

generator/src/main/java/io/github/jwharm/javagi/gir/DocStability.java, generator/src/main/java/io/github/jwharm/javagi/gir/GirElement.java, generator/src/main/java/io/github/jwharm/javagi/gir/GirParser.java, generator/src/main/java/io/github/jwharm/javagi/gir/InfoElements.java
Apparently the Gir `<doc-stability>` element was not supported yet. It is added with this PR.
=> Add support for doc-stability gir element

modules/glib/src/main/java/io/github/jwharm/javagi/interop/MemoryCleaner.java, modules/glib/src/test/java/io/github/jwharm/javagi/interop/ArrayTest.java, modules/glib/src/test/java/io/github/jwharm/javagi/interop/FlagsTest.java, modules/glib/src/test/java/io/github/jwharm/javagi/interop/HashTableTest.java, modules/glib/src/test/java/io/github/jwharm/javagi/interop/MarshalTest.java, modules/glib/src/test/java/io/github/jwharm/javagi/interop/VarargsTest.java
Removed the `reference` counter field because there can always be only one single instance that has ownership.
Clarified the javadoc comments and improved some formatting.
Moved the call to `g_free()` down, below the calls to `g_boxed_free()` and the specialized free-function, to make it more clear that it is a fallback case.
=> Fixed bugs in the MemoryCleaner class

buildSrc/src/main/java/GenerateSources.java, buildSrc/src/main/kotlin/java-gi.library-conventions.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties
* Changed the `GenerateSources` task to be compatible with the Gradle configuration cache (avoid referencing `project` from the task)
* Upgraded Gradle wrapper to 8.11.1
=> Gradle configuration cache

modules/gio/src/main/java/io/github/jwharm/javagi/gio/ListIndexModel.java, modules/gio/src/test/java/io/github/jwharm/javagi/test/gio/ListModelTest.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/annotations/Property.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Properties.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Types.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/PropertyBindingTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/PropertyTest.java, modules/gtk/src/main/java/io/github/jwharm/javagi/gtk/types/TemplateTypes.java
With this PR, Java-GI will automatically create GObject properties for pairs of `get` and `set` methods (also known as JavaBean properties). It is still possible to override this behavior with the existing `@Property` annotation.
The change should be backwards compatible. If not, annotate problematic methods with `@Property(skip=true)`.
=> Auto properties

modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/ValueUtil.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/annotations/Property.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Properties.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/PropertyTest.java
With this PR, it will become possible to specify minimum, maximum and default values for GObject properties declared in Java classes with the `@Property` annotation.
For example:
```java
@Property(minimumValue = "1", maximumValue = "12", defaultValue = "1")
public void setMonth(int month) {
this.month = month;
}
```
The `@Property` parameters `minimumValue`, `maximumValue` and `defaultValue` expect String values. They are transformed by Java-GI to the proper type using `Boolean.parseBoolean()`, `Integer.parseInt()` etcetera.
Using these three parameters, Java developers can set the minimum, maximum and default values on the `GParamSpec` of a property that they defined in Java.
* The minimum and maximum values are not enforced by Java-GI, so on the Java side the benefits are negligible. In …
=> Property minimum, maximum and default values

generator/src/main/java/io/github/jwharm/javagi/generators/UnionGenerator.java
Generate methods defined on `<union>` elements in GIR files.
In the default set of bindings, this will only add a set of methods on `GMutex`. Other types were not impacted.
=> Generate methods for unions

generator/src/main/java/io/github/jwharm/javagi/configuration/ClassNames.java, generator/src/main/java/io/github/jwharm/javagi/generators/AliasGenerator.java, generator/src/main/java/io/github/jwharm/javagi/generators/RecordGenerator.java, generator/src/main/java/io/github/jwharm/javagi/patches/GObjectPatch.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/ToStringTest.java
This PR adds a `toString()` method to the Java classes for GType and GVariant for easier printing and debugging.
The `Type.toString()` method calls `g_type_name()`. It is added on the Type class in GObject, because `g_type_name` is in the GObject namespace, so it's pretty useless as long as Java-GI is completely built around the Type class in GLib.
The `Variant.toString()` method calls `g_variant_print(true)` so it displays both the value and the type information.
=> Add `toString()` methods for GType and GVariant

generator/src/main/java/io/github/jwharm/javagi/JavaGI.java, generator/src/main/java/io/github/jwharm/javagi/generators/TypedValueGenerator.java, generator/src/main/java/io/github/jwharm/javagi/gir/Alias.java, generator/src/main/java/io/github/jwharm/javagi/gir/RegisteredType.java, generator/src/main/java/io/github/jwharm/javagi/patches/GLibPatch.java, modules/gtk/src/test/java/io/github/jwharm/javagi/test/gtk/PangoLayoutLineTest.java
Read- and write-methods for these fields were omitted from the API by mistake, when the custom List and SList classes were introduced.
This PR fixes #173
=> Fix reading and writing fields containing a GList/GSList

generator/src/main/java/io/github/jwharm/javagi/configuration/ClassNames.java, generator/src/main/java/io/github/jwharm/javagi/generators/ClassGenerator.java, generator/src/main/java/io/github/jwharm/javagi/gir/Class.java, generator/src/main/java/io/github/jwharm/javagi/patches/GtkPatch.java, modules/gio/src/main/java/io/github/jwharm/javagi/gio/ListModelJavaList.java, modules/gio/src/main/java/io/github/jwharm/javagi/gio/ListModelJavaListMutable.java, modules/gio/src/main/java/io/github/jwharm/javagi/gio/ListModelJavaListSpliceable.java, modules/gtk/src/test/java/io/github/jwharm/javagi/test/gtk/MutableListTest.java, modules/gtk/src/test/java/io/github/jwharm/javagi/test/gtk/SpliceableListTest.java
Some lists in GTK support mutation via `append`, `remove` and `splice`.
This implements the required methods to allow mutation on them.
Additionally, this allows patches to pick implementation classes for generics where appropriate (like `StringObject` for `StringList` as its documentation suggests)
=> Add support for mutable lists

generator/src/main/java/io/github/jwharm/javagi/configuration/Patches.java, generator/src/main/java/io/github/jwharm/javagi/patches/GstPatch.java
GstMapFlags are defined as a bitfield in gobject-introspection, with additional flags defined in other namespaces. Because java-gi generates an enum by default for a bitfield, the additional flags cannot be used. This PR changes GstMapFlags into integer constants so they can be bitwise-combined manually.
=> Treat GstMapFlags as integers, to allow extended flags (fixes #172)

generator/src/main/java/io/github/jwharm/javagi/generators/ConstructorGenerator.java, generator/src/main/java/io/github/jwharm/javagi/gir/GirElement.java, generator/src/main/java/io/github/jwharm/javagi/patches/GtkPatch.java
Do not override the return type of all constructor functions automatically.
For Gtk Widget constructors, override the return type with a GIR patch.
Fixes #160
=> Return type of constructor functions

generator/src/main/java/io/github/jwharm/javagi/gir/Method.java, generator/src/main/java/io/github/jwharm/javagi/gir/VirtualMethod.java, generator/src/main/java/io/github/jwharm/javagi/patches/GObjectPatch.java, generator/src/main/java/io/github/jwharm/javagi/patches/GioPatch.java, modules/gio/src/main/java/io/github/jwharm/javagi/gio/AutoCloseable.java
Invoker methods for virtual methods can only be combined into one Java method when the type signatures match precisely. This PR adds a check that compares the type signatures.
=> Check invoker method parameter types

generator/src/main/java/io/github/jwharm/javagi/configuration/ClassNames.java, generator/src/main/java/io/github/jwharm/javagi/generators/ClassGenerator.java, modules/glib/src/main/java/io/github/jwharm/javagi/interop/VarargsUtil.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/DerivedClassTest.java
Generate a GObject constructor that takes a Java class as first argument instead of a GType, followed by varargs for (optionally) specifying property names and values.
A new utility class `VarargsUtil` was created that simplifies splitting the varargs into a "first" and "rest" component like `g_object_new` expects, and also adds a `null` at the end, in case the user forgets it.
This was a missing piece from #164.
=> Add GObject constructor that takes a Java class as first argument

generator/src/main/java/io/github/jwharm/javagi/generators/ConstructorGenerator.java
Always generate a static factory method instead of a constructor in Java when the GIR contains constructors in an abstract class. Fixes #184
=> Static factory methods for constructors in abstract classes

.github/workflows/windows-gtk.yml
To make the artifacts built by the GTK CI actually available to users, they need to be downloadable from somewhere.
I had intended GitHub Releases to be that place, but it seems like you didn't enable publishing to it the last time you ran the action (the option to do so was intended for testing, since Actions artifacts get deleted after some time and need login to access, but potentially broken builds shouldn't be released).
With this change, the corresponding checkbox is checked by default, which better represents the intended use.
=> Make updating the release the default action

generator/src/main/java/io/github/jwharm/javagi/generators/ClassGenerator.java, generator/src/main/java/io/github/jwharm/javagi/patches/GioPatch.java
GListStore can be used as a java.util.List, but did not support mutation actions (add, remove, clear etc).
To make this work, the `ListStore.removeItem()` method was renamed to `removeAt()`, and a temporary `@Deprecated removeItem()` was added for backwards compatibility.
=> Let GListStore implement ListModelJavaListMutable

generator/src/main/java/io/github/jwharm/javagi/configuration/ClassNames.java, generator/src/main/java/io/github/jwharm/javagi/generators/ClassGenerator.java, generator/src/main/java/io/github/jwharm/javagi/generators/NamespaceGenerator.java, generator/src/main/java/io/github/jwharm/javagi/generators/TypedValueGenerator.java, generator/src/main/java/io/github/jwharm/javagi/gir/Callable.java, generator/src/main/java/io/github/jwharm/javagi/gir/RegisteredType.java, modules/gio/src/main/java/io/github/jwharm/javagi/gio/ListIndexModel.java, modules/gio/src/test/java/io/github/jwharm/javagi/test/gio/ListModelTest.java, modules/gio/src/test/java/io/github/jwharm/javagi/test/gio/PropertiesTest.java, modules/glib/src/main/java/io/github/jwharm/javagi/base/ProxyInstance.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/InstanceCache.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/JavaClosure.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Overrides.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Properties.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/TypeCache.java, modules/gobject/src/main/java/io/github/jwharm/javagi/gobject/types/Types.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/ClosureTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/CustomInterfaceTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/DerivedClassTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/NewSignalTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/PropertyBindingTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/PropertyTest.java, modules/gobject/src/test/java/io/github/jwharm/javagi/test/gobject/ToStringTest.java, modules/gtk/src/main/java/io/github/jwharm/javagi/gtk/types/TemplateTypes.java, modules/gtk/src/main/java/io/github/jwharm/javagi/gtk/util/BuilderJavaScope.java, modules/gtk/src/test/java/io/github/jwharm/javagi/test/gtk/TemplateChildTest.java, modules/gtk/src/test/java/io/github/jwharm/javagi/test/gtk/TemplateSignalTest.java
This PR refactors the Java-GI logic for registration and construction of GObject-derived classes.
- All generated GObject-derived classes now have a public constructor that takes a varargs parameter of property names and values.
- User-defined GObject-derived classes can user `super(...)` during construction. The `MemorySegment` constructor is not necessary anymore.
- When constructing an instance of a user-defined GObject-derived Java class, the Java instance will first be created (pointing to memory address `null`) and then `g_object_new` will be called. The Java instance will then be used for the instance initialization, and the memory address will be updated to the new GObject's address. This means it is no longer necessary to use static factory methods for construction.
- When a …
=> Refactor gobject constructors

generator/src/main/java/io/github/jwharm/javagi/generators/ClassGenerator.java
Java-GI generates an inner class `Builder` and a static `builder()` method to create one. However, for abstract classes the `builder()` method shouldn't be generated. The `Builder` class should still exist, but it can only be used from subclasses, and not created directly.
=> Don't generate a `builder()` method in abstract classes

generator/src/main/java/io/github/jwharm/javagi/generators/ConstructorGenerator.java
For named constructors, Java-GI generates a static factory method. This method calls the native constructor function, and then calls `InstanceCache.getForType()` to wrap it in a Java proxy object with the correct class. Finally, it calls `object.ref()` on the object, but this is unnecessary because the InstanceCache already added a toggle reference. This will prevent the object from being garbage-collected later, so it's a memory leak. This PR removes the double `ref()`.
=> Fix double `ref()` in static factory methods

generator/src/main/java/io/github/jwharm/javagi/generators/MethodGenerator.java, generator/src/main/java/io/github/jwharm/javagi/generators/PostprocessingGenerator.java, generator/src/main/java/io/github/jwharm/javagi/generators/TypedValueGenerator.java, generator/src/main/java/io/github/jwharm/javagi/gir/AnyType.java, generator/src/main/java/io/github/jwharm/javagi/gir/Array.java, generator/src/main/java/io/github/jwharm/javagi/gir/Boxed.java, generator/src/main/java/io/github/jwharm/javagi/gir/FieldContainer.java, generator/src/main/java/io/github/jwharm/javagi/gir/InstanceParameter.java, generator/src/main/java/io/github/jwharm/javagi/gir/Parameter.java, generator/src/main/java/io/github/jwharm/javagi/gir/Property.java, generator/src/main/java/io/github/jwharm/javagi/gir/Record.java, generator/src/main/java/io/github/jwharm/javagi/gir/RegisteredType.java, generator/src/main/java/io/github/jwharm/javagi/gir/ReturnValue.java, generator/src/main/java/io/github/jwharm/javagi/gir/StandardLayoutType.java, generator/src/main/java/io/github/jwharm/javagi/gir/Type.java, generator/src/main/java/io/github/jwharm/javagi/gir/TypedValue.java, generator/src/main/java/io/github/jwharm/javagi/gir/Union.java, modules/glib/src/main/java/io/github/jwharm/javagi/interop/Interop.java
This PR merges a lot of the code that handles return values and out-parameters (take ownership, free native memory, check for null, etc). This code is now done in post-processing statements for both return values and out-parameters. As a result, all return values are now stored in a `_returnValue` variable before being returned. The post-processing statements (if any) are generated between those lines.
This not only improves the code generator internally (the MethodGenerator is now a lot simpler) but it also fixes bugs because out-parameters didn't always free native memory when they should. `soup_form_decode_multipart` is an example of this, that should now be fixed.
=> Postprocessing changes

generator/src/main/java/io/github/jwharm/javagi/configuration/ClassNames.java, generator/src/main/java/io/github/jwharm/javagi/generators/NamespaceGenerator.java, generator/src/main/java/io/github/jwharm/javagi/patches/GLibPatch.java
The GLib functions `g_idle_add_once`, `g_timeout_add_once` and `g_timeout_add_seconds_once` don't notify the caller when the callback function has finished. This causes a memory leak in Java-GI, because the arena in which the callback upcall stub was allocated, is never closed.
Because these three functions are simple wrappers around `g_idle_add_full`, `g_timeout_add_full` and `g_timeout_add_seconds_full`, which do notify the caller to free the callback allocation, they have been reimplemented in Java as custom wrappers that call the "full" functions and then return `G_SOURCE_REMOVE`.
=> Fix memory leaks in GLib callback functions

generator/src/main/java/io/github/jwharm/javagi/generators/DocGenerator.java
This generates "@since" tags in Javadoc comments when the GIR file contains a "version" attribute.
The version refers to the native library version, not the Java-GI version.
=> Generate "@since" javadoc tags

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/java-gi.library-conventions.gradle.kts, gradle.properties, gradle/libs.versions.toml
As recommended by Sonatype, I've configured JReleaser to publish Java-GI artifacts to Maven Central Portal (instead of the old OSSRH staging api).
=> Publish to Maven Central Portal with JReleaser

modules/glib/src/main/java/io/github/jwharm/javagi/interop/MemoryCleaner.java
Avoids the potential memory corruption as described in #222
=> Run cleanable immediately when calling yieldOwnership (fixes #222)

generator/src/main/java/org/javagi/generators/AliasGenerator.java, generator/src/main/java/org/javagi/generators/CallableGenerator.java, generator/src/main/java/org/javagi/generators/MemoryLayoutGenerator.java, generator/src/main/java/org/javagi/generators/SignalGenerator.java, generator/src/main/java/org/javagi/generators/TypedValueGenerator.java, generator/src/main/java/org/javagi/gir/Type.java, generator/src/main/java/org/javagi/util/Conversions.java
When a struct is passed by value to a native function, we have to set the struct's memory layout in the FunctionDescriptor, not ValueLayout.ADDRESS.
This means we can't use simple strings ("ADDRESS", "JAVA_INT" etc.) to represent the memory layout anymore, because we need to include things like "typeName:T.getMemoryLayout()". So the relevant functions have been changed everywhere to use PartialStatements that maintain the relevant type information.
=> Fix memory layout generation for struct parameters

generator/src/main/java/org/javagi/generators/PostprocessingGenerator.java, generator/src/main/java/org/javagi/generators/PreprocessingGenerator.java, generator/src/main/java/org/javagi/generators/TypedValueGenerator.java, generator/src/main/java/org/javagi/gir/RegisteredType.java, generator/src/main/java/org/javagi/gir/TypeReference.java, generator/src/main/java/org/javagi/metadata/MetadataParser.java, generator/src/main/java/org/javagi/util/Conversions.java, generator/src/main/resources/metadata/GLib-2.0.metadata, generator/src/main/resources/metadata/GObject-2.0.metadata, modules/main/glib/src/main/java/org/javagi/interop/Interop.java, modules/main/glib/src/test/java/org/javagi/glib/BytesTest.java, modules/main/glib/src/test/java/org/javagi/glib/MarshalTest.java
With this PR, `GString` is marshaled to and from `java.lang.String` automatically by Java-GI. The class `org.gnome.glib.GString` is no longer generated.
=> Marshal GString from and to Java String

buildSrc/src/main/kotlin/java-gi.module.gradle.kts, generator/src/main/java/org/javagi/generators/NamespaceGenerator.java, generator/src/main/java/org/javagi/generators/PostprocessingGenerator.java, generator/src/main/java/org/javagi/gir/Repository.java, modules/main/gobject/src/main/java/org/javagi/gobject/ValueUtil.java, modules/main/gobject/src/main/java/org/javagi/gobject/types/Properties.java, modules/main/gobject/src/main/java/org/javagi/gobject/types/TypeCache.java, modules/main/gobject/src/test/java/org/javagi/gobject/ClosureTest.java, modules/test/gimarshallingtests/src/test/java/org/javagi/gimarshallingtests/TestObjectProperties.java
Java-GI will now register boxed types in the TypeCache, so when a GValue contains a boxed value, Java-GI is able to construct the expected Java  proxy class instance.
Also added handling of GStrv GValues, so they are automatically converted from and to Java String[].
The GValue conversion functions will now throw an UnsupportedOperationException when a type cannot be convered.
=> Improve handling of GValues with boxed types and string arrays

generator/src/main/java/org/javagi/configuration/ClassNames.java, generator/src/main/java/org/javagi/generators/RecordGenerator.java, modules/main/glib/src/main/java/org/javagi/interop/Variants.java, modules/main/glib/src/test/java/org/javagi/glib/VariantTest.java, modules/test/regress/src/test/java/org/javagi/regress/TestVariant.java
This adds three new methods to the `org.gnome.glib.Variant` class:
* `public static Variant pack(Object object)` to create a Variant from a Java Object
* `public Object unpack()` to unpack a Variant to a Java Object
* `public Object unpackRecursive()` to unpack a Variant to a Java Object, recursively unpacking nested Variants too.
In most cases, packing and unpacking an object will result in an object that equals the original, but this is not always the case, because during the pack/unpack operations, some information gets lost. For example:
* A Variant with an unsigned datatype is unpacked to a signed Java value
* A Variant with an object path or type signature is unpacked to a Java String
* Conversely, both Java `List` and `Set` are packed into an array-type Variant
* A Java …
=> Add GVariant pack and unpack methods

generator/src/main/java/org/javagi/generators/ClosureGenerator.java, modules/main/glib/src/main/java/org/javagi/base/GErrorException.java
This PR makes fixes some GError ownership issues.
Also, `GError.literal()` is used instead of `new GError()` so the message isn't interpreted as a printf-style formatted text.
=> Fix GError ownership when set from a Java callback

generator/src/main/java/org/javagi/configuration/ModuleInfo.java, modules/rsvg/build.gradle.kts, settings.gradle.kts
Add bindings for LibRsvg
The bindings are in a new module, with one package: `org.gnome.rsvg`.
An example will be added later to the java-gi-examples repository.
=> Add bindings for librsvg
